### ISSUE TITLE
tcmu get some errors.  iscsi-initiator successful log in ! but not attached  any SCSI devices??

### ISSUE THREAD

**Issue by madison-c** [open-iscsi/tcmu-runner#623] opened 2020-04-22 14:31 UTC
# server 
[root@iscsi01 ~]# rpm -qa |grep tcmu
libtcmu-1.5.2-1.el7.x86_64
tcmu-runner-1.5.2-1.el7.x86_64
[root@iscsi01 ~]# uname  -a
Linux iscsi01.ceph.com 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
# tcmu-runner.log 
2020-04-22 10:26:20.620 4236 [WARN] tcmu_get_alua_grp:226 rbd/rbd.disk01: Unsupported alua_access_type: Implicit and Explicit failover not supported.
2020-04-22 10:26:20.620 4236 [ERROR] tcmu_get_alua_grps:320 rbd/rbd.disk01: Could not get alua group ao.
2020-04-22 10:26:20.667 4236 [WARN] tcmu_get_alua_grp:226 rbd/rbd.image01: Unsupported alua_access_type: Implicit and Explicit failover not supported.
2020-04-22 10:26:20.667 4236 [ERROR] tcmu_get_alua_grps:320 rbd/rbd.image01: Could not get alua group ao.
2020-04-22 10:26:25.688 4236 [CRIT] main:1390: Exiting...
2020-04-22 10:26:31.163 4300 [WARN] tcmu_get_alua_grp:226 rbd/rbd.disk01: Unsupported alua_access_type: Implicit and Explicit failover not supported.
2020-04-22 10:26:31.163 4300 [ERROR] tcmu_get_alua_grps:320 rbd/rbd.disk01: Could not get alua group ao.
2020-04-22 10:26:31.190 4300 [WARN] tcmu_get_alua_grp:226 rbd/rbd.image01: Unsupported alua_access_type: Implicit and Explicit failover not supported.
2020-04-22 10:26:31.190 4300 [ERROR] tcmu_get_alua_grps:320 rbd/rbd.image01: Could not get alua group ao.

# client

[root@iscsi01 ~]#  iscsiadm --mode node -l
Logging in to [iface: default, target: iqn.2020-04.com.redhat.iscsi-gw:ceph-igw, portal: 172.16.120.180,3260] (multiple)
Logging in to [iface: default, target: iqn.2020-04.com.redhat.iscsi-gw:ceph-igw, portal: 172.16.120.181,3260] (multiple)
Login to [iface: default, target: iqn.2020-04.com.redhat.iscsi-gw:ceph-igw, portal: 172.16.120.180,3260] successful.
Login to [iface: default, target: iqn.2020-04.com.redhat.iscsi-gw:ceph-igw, portal: 172.16.120.181,3260] successful.
[root@iscsi01 ~]# lsblk 
NAME            MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda               8:0    0  30G  0 disk 
├─sda1            8:1    0   1G  0 part /boot
└─sda2            8:2    0  29G  0 part 
  ├─centos-root 253:0    0  27G  0 lvm  /
  └─centos-swap 253:1    0   2G  0 lvm  [SWAP]

                ************************
                Negotiated iSCSI params:
                ************************
                HeaderDigest: None
                DataDigest: None
                MaxRecvDataSegmentLength: 262144
                MaxXmitDataSegmentLength: 262144
                FirstBurstLength: 65536
                MaxBurstLength: 262144
                ImmediateData: Yes
                InitialR2T: Yes
                MaxOutstandingR2T: 1
                ************************
                Attached SCSI devices:
                ************************
                Host Number: 21 State: running

**Comment by madison-c** [comment] 2020-04-29 01:36
any one ?

**Comment by madison-c** [comment] 2020-04-29 01:41
hello !  anybody  help me slove this problem.

**Comment by madison-c** [comment] 2020-04-29 01:44
hello ! anybody help me slove this problem.

**Comment by lxbsz** [comment] 2020-04-29 02:28
What version of the iscsi-gw you are using ? Why did you set the alua_access_type to 3 or " Implicit and Explicit" ? 

Currently tcmu-runner only supports alua_access_type = {0, 1} or {"None", "Implicit"}.

You can manually set it back by using the following commands, something like:

`# echo 1 > /sys/kernel/config/target/core/user_0/block0/alua/glfs_tg_pt_gp_ano/alua_access_type
`
Or 

`# targetcli /backstores/user:glfs/block0/alua/glfs_tg_pt_gp_ano set alua alua_access_type=1`

**Comment by madison-c** [comment] 2020-04-29 03:31
@lxbsz thks man!  below is my pkg version:


	[root@ceph-gw-1 ~]# rpm -qa |egrep  'iscsi|tcmu'
	libtcmu-1.5.2-1.el7.x86_64
	ceph-iscsi-config-2.6-2.6.el7.noarch
	ceph-iscsi-cli-2.7-2.7.el7.noarch
	tcmu-runner-1.5.2-1.el7.x86_64

	[root@ceph-gw-1 ~]# ceph -v
	ceph version 13.2.8 (5579a94fafbc1f9cc913a0f5d362953a5d9c3ae0) mimic (stable)
	
and I have no spec configuration. 
where to define alua_access_type  permanently?

**Comment by lxbsz** [comment] 2020-04-29 04:47
You could edit it in /etc/target/saveconfig.json

**Comment by mikechristie** [comment] 2020-04-29 15:55
Are you using the ceph-iscsi tools to setup the device or a are you manually setting it with targetcli or via configfs?

The problem is that you have set unsupported ALUA values, so the target is not creating the LUNs. There is then nothing on the initiator side to see.

If you are using the ceph-iscsi tools to set things up then you have a mismatch between the ceph-icsi tools and tmcu-runner.

You should upgrade to the newest ceph-iscsi-config/ceph-iscsi-cli tools or use the newer ceph-iscsi (https://github.com/ceph/ceph-iscsi) version of the tools (that repo merged both projects and is where new development is going).

**Closed** 2020-05-15 17:21 UTC
